// Builds js/words.js from the public-domain ENABLE word list (enable1.txt).
//
//   curl -o enable1.txt https://raw.githubusercontent.com/dolph/dictionary/master/enable1.txt
//   node tools/build-words.js enable1.txt
//
// The source is checked against the SHA-256 recorded in CREDITS.md so a
// changed upstream file can't slip in unnoticed. Words longer than the
// 15-square board are dropped, since they can never be played.
"use strict";
const crypto = require("crypto");
const fs = require("fs");
const path = require("path");

const EXPECTED_SHA256 = "3f16130220645692ed49c7134e24a18504c2ca55b3c012f7290e3e77c63b1a89";
const BOARD = 15;

function main(source) {
  if (!source) throw new Error("usage: node tools/build-words.js <enable1.txt>");
  const raw = fs.readFileSync(source);
  const sha = crypto.createHash("sha256").update(raw).digest("hex");
  if (sha !== EXPECTED_SHA256) throw new Error("unexpected word list (sha256 " + sha + "); see CREDITS.md");
  const words = raw.toString("ascii").split("\n").filter(Boolean);
  if (!words.every((w) => /^[a-z]+$/.test(w))) throw new Error("word list has lines that aren't lowercase a-z");
  const playable = words.filter((w) => w.length >= 2 && w.length <= BOARD).map((w) => w.toUpperCase());
  const out = [
    "// Generated by tools/build-words.js from the ENABLE word list (public domain; see CREDITS.md).",
    "// " + playable.length + " words of 2-" + BOARD + " letters, sorted, newline-separated. Do not edit by hand.",
    "(function (root) {",
    "  \"use strict\";",
    "  const WORDS = " + JSON.stringify(playable.join("\n")) + ";",
    "  if (typeof module !== \"undefined\" && module.exports) module.exports = WORDS;",
    "  else root.WORD_GRID_WORDS = WORDS;",
    "})(typeof window !== \"undefined\" ? window : globalThis);",
    "",
  ].join("\n");
  const target = path.join(__dirname, "..", "js", "words.js");
  fs.writeFileSync(target, out);
  console.log("wrote " + target + ": " + playable.length + " words, " + out.length + " bytes");
}

main(process.argv[2]);
